name: FireShop
description: Le système de gestion des stocks 
full_description: 'Fireshop est une application destinée aux Boutiques. Elle permet de gérer vos produits et la relation avec vos clients. Du chargement de Stock, à la vente aux clients.<br>
<br>Avec beaucoup de fonctionnalités:
<br>- Interface utilisateur et UX conviviales et belle fenêtre.
<br>- ⚡ Stockage de données en Cloud.
<br>- 🚚 Gestion des produits,clients et commandes.
<br>- 📉 Statistiques et Graphique de la semaine (NOUVEAU!!!).
<br>- 📑 Produits les plus vendus.
<br>- 🔑 Paramètres de profil'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
  - 6.png
  - 7.png
  - 8.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
